version: '3.8'

services:
  web:
    build:
      context: ./web  # Directory containing the Dockerfile
      dockerfile: Dockerfile  # Optional if the file is named Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
    environment:
      FLASK_ENV: development

  worker:
    build:
      context: ./worker  # Directory containing the Dockerfile
      dockerfile: Dockerfile  # Optional if the file is named Dockerfile
    volumes:
      - ./worker:/app
    environment:
      TASK_QUEUE: celery
